export const ADD_SONGS = 'ADD_SONGS';
export const ADD_SONGS_TO_TOP = 'ADD_SONGS_TO_TOP';
export const ADD_STREAM_TO_TOP = 'ADD_STREAM_TO_TOP';
export const ADD_SONGS_TO_TOP_AND_PLAY = 'ADD_SONGS_TO_TOP_AND_PLAY';
export const REMOVE_SONGS = 'REMOVE_SONGS';

export const GET_AND_UPDATE_AUTOCOMPLETE = 'GET_AND_UPDATE_AUTOCOMPLETE';
export const UPDATE_AUTOCOMPLETE = 'UPDATE_AUTOCOMPLETE';

export const UPDATE_SEARCH_QUEUE = 'UPDATE_SEARCH_QUEUE';
export const SEARCH_SONGS = 'SEARCH_SONGS';
export const SEARCH_AND_UPDATE_SEARCH_QUEUE = 'SEARCH_AND_UPDATE_SEARCH_QUEUE';

export const PLAY = 'PLAY';
export const PAUSE = 'PAUSE';
export const CLEAN_PLAYER = 'CLEAN_PLAYER';
export const SET_PLAYING_SONG = 'SET_PLAYING_SONG';
export const SET_PLAYING_SONG_ID = 'SET_PLAYING_SONG_ID';
export const SET_VOLUME = 'SET_VOLUME';
export const SET_PROGRESS = 'SET_PROGRESS';
export const PLAY_NEXT = 'PLAY_NEXT';
export const PLAY_PREV = 'PLAY_PREV';
export const SEEK_TO = 'SEEK_TO';
export const SET_SEEKING = 'SET_SEEKING';

export const AUTH_USER = 'AUTH_USER';
export const SET_USER_DATA = 'SET_USER_DATA';
export const UPDATE_CURRENT_USER_DATA = 'UPDATE_CURRENT_USER_DATA';
export const CLEAN_SESSION = 'CLEAN_SESSION';
export const SET_ECHO_CLI_SESSION = 'SET_ECHO_CLI_SESSION';

export const GET_STREAMS = 'GET_STREAMS';
export const SET_MY_STREAMS = 'SET_MY_STREAMS';
export const CLEAN_MY_STREAMS = 'CLEAN_MY_STREAMS';
export const UPDATE_STREAM = 'UPDATE_STREAM';
export const LIKE_STREAM = 'LIKE_STREAM';
export const UNLIKE_STREAM = 'UNLIKE_STREAM';
export const UPLOAD_ARTWORK = 'UPLOAD_ARTWORK';
export const CREATE_STREAM = 'CREATE_STREAM';
