export const ADD_SONGS = 'ADD_SONGS';
export const REMOVE_SONGS = 'REMOVE_SONGS';

export const UPDATE_SEARCH_AUTOCOMPLETE = 'UPDATE_SEARCH_AUTOCOMPLETE';

export const UPDATE_SEARCH_QUEUE = 'UPDATE_SEARCH_QUEUE';
export const SEARCH_SONGS = 'SEARCH_SONGS';
export const SEARCH_AND_UPDATE_SEARCH_QUEUE = 'SEARCH_AND_UPDATE_SEARCH_QUEUE';
